title: schdck's website
email: mauricio.schmaedeck@gmail.com
description: >-
  Here, hopefully, I'll post a few stuff about me and some of the bits I put together.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schdck.github.io"
twitter_username: schmaedeck
github_username: schdck
stackoverflow_id: 5686352
steam_id: schdck
repository: schdck/schdck.github.io
logo: https://avatars0.githubusercontent.com/u/16804291?s=460&v=4

markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed