title: schdck's blog
url: "https://schdck.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

repository: schdck/schdck.github.io
markdown: kramdown

remote_theme: schdck/tale
permalink:    /:title
paginate:     10

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

author:
  name: schdck
  twitter_username: schmaedeck
  github_username: schdck
  stackoverflow_id: 5686352
  steam_id: schdck
  image: https://avatars0.githubusercontent.com/u/16804291?s=460&v=4
  email: mauricio.schmaedeck <i>at</i> gmail.com
  short_bio: My name is Maurício Vielmo Schmaedeck and I'm from Brazil.In this blog, hopefully, I'll post a few stuff about some of the bits I put together.